"""Authentication table

Revision ID: 485e1728aef7
Revises: 
Create Date: 2026-03-22 11:45:35.504494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '485e1728aef7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesstokenblocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesstokenblocklist_token'), 'accesstokenblocklist', ['token'], unique=False)
    op.create_index(op.f('ix_accesstokenblocklist_token_type'), 'accesstokenblocklist', ['token_type'], unique=False)
    op.create_table('refreshtokenblocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtokenblocklist_token'), 'refreshtokenblocklist', ['token'], unique=False)
    op.create_index(op.f('ix_refreshtokenblocklist_token_type'), 'refreshtokenblocklist', ['token_type'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_refreshtokenblocklist_token_type'), table_name='refreshtokenblocklist')
    op.drop_index(op.f('ix_refreshtokenblocklist_token'), table_name='refreshtokenblocklist')
    op.drop_table('refreshtokenblocklist')
    op.drop_index(op.f('ix_accesstokenblocklist_token_type'), table_name='accesstokenblocklist')
    op.drop_index(op.f('ix_accesstokenblocklist_token'), table_name='accesstokenblocklist')
    op.drop_table('accesstokenblocklist')
    # ### end Alembic commands ###
